CREATE TABLE salas (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nome VARCHAR(255) NOT NULL UNIQUE,
                       localizacao VARCHAR(255) NOT NULL,
                       responsavel VARCHAR(255) NOT NULL,
                       capacidade INTEGER
);

CREATE TABLE agendamentos (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              sala_id BIGINT NOT NULL,
                              data DATE NOT NULL,
                              hora_inicio TIME NOT NULL,
                              hora_fim TIME NOT NULL,

                              CONSTRAINT fk_agendamento_sala
                                  FOREIGN KEY (sala_id)
                                      REFERENCES salas(id)
);

CREATE TABLE permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255)


);

CREATE TABLE users (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   userName VARCHAR(255) NOT NULL,
   fullName VARCHAR(255),
   password VARCHAR(255),
   account_non_expired BOOLEAN NOT NULL DEFAULT TRUE,
   account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
   credentials_non_expired BOOLEAN NOT NULL DEFAULT TRUE,
   enabled BOOLEAN NOT NULL DEFAULT TRUE,

   CONSTRAINT uk_users_userName UNIQUE (userName)
);

CREATE TABLE user_permission (
                                 id_user BIGINT NOT NULL,
                                 id_permission BIGINT NOT NULL,

                                 PRIMARY KEY (id_user, id_permission),

                                 CONSTRAINT fk_user_permission_user
                                     FOREIGN KEY (id_user)
                                         REFERENCES users(id),

                                 CONSTRAINT fk_user_permission_permission
                                     FOREIGN KEY (id_permission)
                                         REFERENCES permission(id)
);