INSERT INTO salas (nome, localizacao, responsavel, capacidade) VALUES
                                                                   ('SA-101', 'Rua das Palmeiras, 1º andar, Prédio A', 'Ana Carolina Ferreira', 20),
                                                                   ('SA-102', 'Rua das Palmeiras, 1º andar, Prédio A', 'Bruno Henrique Silva', 15),
                                                                   ('SA-110', 'Rua das Palmeiras, 1º andar, Prédio A', 'Carla Regina Souza', 30),
                                                                   ('SA-115', 'Rua das Palmeiras, 1º andar, Prédio A', 'Diego Augusto Lima', 25),
                                                                   ('SA-120', 'Rua das Palmeiras, 2º andar, Prédio A', 'Elaine Cristina Rocha', 40),
                                                                   ('SA-125', 'Rua das Palmeiras, 2º andar, Prédio A', 'Fábio Rodrigo Alves', 12),
                                                                   ('SA-130', 'Rua das Palmeiras, 2º andar, Prédio A', 'Gabriela Martins Costa', 50),
                                                                   ('SA-135', 'Rua das Palmeiras, 2º andar, Prédio A', 'Henrique Barbosa Dias', 18),
                                                                   ('SA-140', 'Rua das Palmeiras, 3º andar, Prédio A', 'Isabela Cristina Nunes', 60),
                                                                   ('SA-145', 'Rua das Palmeiras, 3º andar, Prédio A', 'João Pedro Cardoso', 22),
                                                                   ('SA-201', 'Avenida das Acácias, 1º andar, Prédio B', 'Karina Beatriz Melo', 35),
                                                                   ('SA-210', 'Avenida das Acácias, 1º andar, Prédio B', 'Lucas Eduardo Pereira', 10),
                                                                   ('SA-220', 'Avenida das Acácias, 2º andar, Prédio B', 'Mariana Vitória Gomes', 45),
                                                                   ('SA-230', 'Avenida das Acácias, 2º andar, Prédio B', 'Nelson Ricardo Teixeira', 28),
                                                                   ('SA-240', 'Avenida das Acácias, 3º andar, Prédio B', 'Otávio César Ramos', 70),
                                                                   ('SA-250', 'Avenida das Acácias, 3º andar, Prédio B', 'Patrícia Helena Freitas', 16),
                                                                   ('SA-301', 'Rua dos Ipês, 1º andar, Prédio C', 'Quésia Aparecida Moreira', 80),
                                                                   ('SA-310', 'Rua dos Ipês, 2º andar, Prédio C', 'Rafael Augusto Batista', 33),
                                                                   ('SA-320', 'Rua dos Ipês, 3º andar, Prédio C', 'Sabrina Luiza Correia', 55),
                                                                   ('SA-330', 'Rua dos Ipês, 4º andar, Prédio C', 'Thiago Vinícius Araújo', 100),
                                                                   ('RE-101', 'Rua das Orquídeas, 1º andar, Prédio D', 'Vinícius Almeida Torres', 12),
                                                                   ('RE-102', 'Rua das Orquídeas, 1º andar, Prédio D', 'Aline Fernandes Rocha', 18),
                                                                   ('RE-201', 'Rua das Orquídeas, 2º andar, Prédio D', 'Marcelo Souza Pinto', 25),
                                                                   ('AU-301', 'Avenida Central, 3º andar, Prédio E', 'Juliana Costa Ribeiro', 100),
                                                                   ('AU-302', 'Avenida Central, 3º andar, Prédio E', 'Roberto Carlos Machado', 90),
                                                                   ('LB-101', 'Rua dos Girassóis, 1º andar, Prédio F', 'Camila Duarte Barros', 30),
                                                                   ('LB-102', 'Rua dos Girassóis, 1º andar, Prédio F', 'Fernando Luiz Cavalcante', 28),
                                                                   ('LB-110', 'Rua dos Girassóis, 2º andar, Prédio F', 'Beatriz Almeida Santana', 35),
                                                                   ('TR-201', 'Avenida Brasil, 2º andar, Prédio G', 'Rodrigo Nascimento Vieira', 15),
                                                                   ('TR-202', 'Avenida Brasil, 2º andar, Prédio G', 'Larissa Monteiro Castro', 20),
                                                                   ('CO-401', 'Rua das Hortências, 4º andar, Prédio H', 'Eduardo Pires Andrade', 40),
                                                                   ('CO-402', 'Rua das Hortências, 4º andar, Prédio H', 'Tatiane Regina Lopes', 45),
                                                                   ('IN-501', 'Avenida Paulista, 5º andar, Prédio I', 'Gustavo Henrique Farias', 60),
                                                                   ('IN-502', 'Avenida Paulista, 5º andar, Prédio I', 'Priscila Andrade Souza', 55),
                                                                   ('WS-601', 'Rua das Camélias, 6º andar, Prédio J', 'Leonardo Matos Xavier', 10),
                                                                   ('WS-602', 'Rua das Camélias, 6º andar, Prédio J', 'Renata Cristina Moura', 14),
                                                                   ('EV-701', 'Avenida das Nações, 7º andar, Prédio K', 'Alexandre Ferreira Dias', 100),
                                                                   ('CT-801', 'Rua São João, 8º andar, Prédio L', 'Sandra Beatriz Melo', 22),
                                                                   ('DP-901', 'Avenida Rio Branco, 9º andar, Prédio M', 'Márcio Antônio Rezende', 33),
                                                                   ('EX-1001', 'Rua da Consolação, 10º andar, Prédio N', 'Vanessa Oliveira Nogueira', 48);
